// Generated by the in-game collider editor.
export default {
  "facility:cutting-table": {
    "left": 3,
    "right": -2,
    "top": 3,
    "bottom": 0
  },
  "facility:gas-stove": {
    "left": 0,
    "right": 0,
    "top": 18,
    "bottom": 0
  },
  "facility:serving-table": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "facility:shower": {
    "left": 0,
    "right": 0,
    "top": 21,
    "bottom": 0
  },
  "facility:table": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "facility:toilet": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "furniture:bed": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "resource:log-large": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "resource:log-small": {
    "left": 3,
    "right": -4,
    "top": 2,
    "bottom": -4
  },
  "resource:ruby-node": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "resource:stone-large": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "resource:stone-small": {
    "left": 0,
    "right": 0,
    "top": 0,
    "bottom": 0
  },
  "resource:tree-planted": {
    "left": 0,
    "right": 0,
    "top": -12,
    "bottom": -13
  }
};
