export const COLLIDER_DEBUG_STORAGE_KEY = "nestledBurrow.colliderDebug";
export const COLLIDER_DEFAULTS_SAVE_ENDPOINT = "__nestledburrow/save-collider-defaults";

export function normalizeColliderOverrides(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  const result = {};
  for (const [id, candidate] of Object.entries(value).sort(([left], [right]) => left.localeCompare(right))) {
    if (!candidate || typeof candidate !== "object" || Array.isArray(candidate)) continue;
    const offsets = {};
    let valid = true;
    for (const key of ["left", "right", "top", "bottom"]) {
      const number = Number(candidate[key]);
      if (!Number.isFinite(number)) { valid = false; break; }
      offsets[key] = Math.max(-64, Math.min(64, Math.round(number)));
    }
    if (valid) result[id] = offsets;
  }
  return result;
}

export function mergeColliderOverrides(projectDefaults = {}, localOverrides = {}) {
  return normalizeColliderOverrides({
    ...normalizeColliderOverrides(projectDefaults),
    ...normalizeColliderOverrides(localOverrides),
  });
}

export function createColliderDefaultsModuleSource(value) {
  const normalized = normalizeColliderOverrides(value);
  return `// Generated by the in-game collider editor.\nexport default ${JSON.stringify(normalized, null, 2)};\n`;
}

export function loadColliderDebugOverrides(storage = globalThis.localStorage) {
  try {
    return normalizeColliderOverrides(JSON.parse(storage?.getItem(COLLIDER_DEBUG_STORAGE_KEY) ?? "{}"));
  } catch {
    return {};
  }
}

export function saveColliderDebugOverrides(overrides, storage = globalThis.localStorage) {
  try {
    storage?.setItem(COLLIDER_DEBUG_STORAGE_KEY, JSON.stringify(normalizeColliderOverrides(overrides)));
    return true;
  } catch {
    return false;
  }
}

function markLocalColliderSave(error, normalized) {
  const failure = error instanceof Error ? error : new Error(String(error));
  failure.localSaved = true;
  failure.savedValue = normalized;
  return failure;
}

export async function saveColliderDebugOverridesToProject(overrides, {
  storage = globalThis.localStorage,
  fetchImpl = globalThis.fetch,
  baseUrl = import.meta.env?.BASE_URL ?? "/",
} = {}) {
  if (typeof fetchImpl !== "function") throw new Error("Fetch is unavailable");
  const normalized = normalizeColliderOverrides(overrides);
  saveColliderDebugOverrides(normalized, storage);
  try {
    const response = await fetchImpl(`${baseUrl}${COLLIDER_DEFAULTS_SAVE_ENDPOINT}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(normalized),
    });
    if (!response?.ok) {
      const detail = await response?.text?.().catch?.(() => "") ?? "";
      throw new Error(detail || `Authoring endpoint returned HTTP ${response?.status ?? "unknown"}`);
    }
  } catch (error) {
    throw markLocalColliderSave(error, normalized);
  }
  storage?.removeItem?.(COLLIDER_DEBUG_STORAGE_KEY);
  return normalized;
}
